on: 
  push: 
    paths:
      - README.md
      
name: TOC Generator
jobs:
  generateTableOfContent:
    name: Table of Content Generator
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/toc-generator@v4
        with:
          TOC_TITLE: ''
